### ISSUE TITLE
Can I transform your reference.py into an .ipynb version?

### ISSUE THREAD

**Issue by RamonYeung** [justmarkham/python-reference#1]
I noticed that this script has  no displaying with results. For a fishman-friendly interaction, I highly suggest that we transform it into an .ipynb version.

What do you think?

BTW, thanks for the materials provided in your repo. :)

**Comment by justmarkham** [comment]
I added a notebook version... hooray! Thanks for the suggestion :+1: 

You can view it on [GitHub](https://github.com/justmarkham/python-reference/blob/master/reference.ipynb) or using [nbviewer](http://nbviewer.jupyter.org/github/justmarkham/python-reference/blob/master/reference.ipynb).
